services:
  app:
    build:
      context: .
    volumes:
      - ./:/app/html
    command: ["http-server", "./dir"]
    networks:
      - publish

networks:
  publish:
    name: ${PUBLISH_NETWORK}
    external: true